"""BedSpread — pangenome BED peak visualization."""

from bedspread.core import (
    SparseGraphMatrix,
    list_paths,
    clean_path_name,
    extract_path_offset,
    detect_bed_format,
    parse_regionpeak,
    ingest_peak_bed_list,
    build_node_layout,
    build_path_mappings,
    assess_path_linearity,
    build_interval_trees,
    build_sparse_matrix,
    query_nodes,
    export_query_bed,
    bedspread_plot_fast,
    export_static_plot,
    save_sparse_matrix,
    load_sparse_matrix,
    save_sgm_viewer,
    load_sgm_viewer,
    overlay_peaks,
)
from bedspread import interactive, screening

__all__ = [
    "SparseGraphMatrix",
    "list_paths",
    "clean_path_name",
    "extract_path_offset",
    "detect_bed_format",
    "parse_regionpeak",
    "ingest_peak_bed_list",
    "build_node_layout",
    "build_path_mappings",
    "assess_path_linearity",
    "build_interval_trees",
    "build_sparse_matrix",
    "query_nodes",
    "export_query_bed",
    "bedspread_plot_fast",
    "export_static_plot",
    "save_sparse_matrix",
    "load_sparse_matrix",
    "save_sgm_viewer",
    "load_sgm_viewer",
    "overlay_peaks",
    "interactive",
    "screening",
]
